src/Entity/Zawodnik.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ZawodnikRepository")
 */
class Zawodnik
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $imie;

    /**
     * @ORM\Column(type="date")
     */
    private $data_urodzin;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getImie(): ?string
    {
        return $this->imie;
    }

    public function setImie(string $imie): self
    {
        $this->imie = $imie;

        return $this;
    }

    public function getDataUrodzin(): ?\DateTimeInterface
    {
        return $this->data_urodzin;
    }

    public function setDataUrodzin(\DateTimeInterface $data_urodzin): self
    {
        $this->data_urodzin = $data_urodzin;

        return $this;
    }
}

src/Form/ZawodnikType.php
<?php

namespace App\Form;

use App\Entity\Zawodnik;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\BirthdayType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ZawodnikType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('imie')
            ->add('data_urodzin', BirthdayType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Zawodnik::class,
        ]);
    }
}

src/Controller/ZawodnikController.php
<?php

namespace App\Controller;

use App\Entity\Zawodnik;
use App\Form\ZawodnikType;
use App\Repository\ZawodnikRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/zawodnik")
 */
class ZawodnikController extends AbstractController
{
    /**
     * @Route("/", name="zawodnik_index", methods={"GET"})
     */
    public function index(ZawodnikRepository $zawodnikRepository): Response
    {
        return $this->render('zawodnik/index.html.twig', [
            'zawodniks' => $zawodnikRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="zawodnik_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $zawodnik = new Zawodnik();
        $form = $this->createForm(ZawodnikType::class, $zawodnik);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($zawodnik);
            $entityManager->flush();

            return $this->redirectToRoute('zawodnik_index');
        }

        return $this->render('zawodnik/new.html.twig', [
            'zawodnik' => $zawodnik,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="zawodnik_show", methods={"GET"})
     */
    public function show(Zawodnik $zawodnik): Response
    {
        return $this->render('zawodnik/show.html.twig', [
            'zawodnik' => $zawodnik,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="zawodnik_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Zawodnik $zawodnik): Response
    {
        $form = $this->createForm(ZawodnikType::class, $zawodnik);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('zawodnik_index', [
                'id' => $zawodnik->getId(),
            ]);
        }

        return $this->render('zawodnik/edit.html.twig', [
            'zawodnik' => $zawodnik,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="zawodnik_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Zawodnik $zawodnik): Response
    {
        if ($this->isCsrfTokenValid('delete'.$zawodnik->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($zawodnik);
            $entityManager->flush();
        }

        return $this->redirectToRoute('zawodnik_index');
    }
}

templates/zawodnik/_delete_form.html.twig
<form method="post" action="{{ path('zawodnik_delete', {'id': zawodnik.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ zawodnik.id) }}">
    <button class="btn">Delete</button>
</form>

templates/zawodnik/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/zawodnik/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Zawodnik{% endblock %}

{% block body %}
    <h1>Edit Zawodnik</h1>

    {{ include('zawodnik/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('zawodnik_index') }}">back to list</a>

    {{ include('zawodnik/_delete_form.html.twig') }}
{% endblock %}

templates/zawodnik/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Zawodnik index{% endblock %}

{% block body %}
    <h1>Zawodnik index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Imie</th>
                <th>Data_urodzin</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for zawodnik in zawodniks %}
            <tr>
                <td>{{ zawodnik.id }}</td>
                <td>{{ zawodnik.imie }}</td>
                <td>{{ zawodnik.dataUrodzin ? zawodnik.dataUrodzin|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('zawodnik_show', {'id': zawodnik.id}) }}">show</a>
                    <a href="{{ path('zawodnik_edit', {'id': zawodnik.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('zawodnik_new') }}">Create new</a>
{% endblock %}

templates/zawodnik/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Zawodnik{% endblock %}

{% block body %}
    <h1>Create new Zawodnik</h1>

    {{ include('zawodnik/_form.html.twig') }}

    <a href="{{ path('zawodnik_index') }}">back to list</a>
{% endblock %}

templates/zawodnik/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Zawodnik{% endblock %}

{% block body %}
    <h1>Zawodnik</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ zawodnik.id }}</td>
            </tr>
            <tr>
                <th>Imie</th>
                <td>{{ zawodnik.imie }}</td>
            </tr>
            <tr>
                <th>Data_urodzin</th>
                <td>{{ zawodnik.dataUrodzin ? zawodnik.dataUrodzin|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('zawodnik_index') }}">back to list</a>

    <a href="{{ path('zawodnik_edit', {'id': zawodnik.id}) }}">edit</a>

    {{ include('zawodnik/_delete_form.html.twig') }}
{% endblock %}